Repository Apollo-Spreadsheet/apollo-spreadsheet, pull requests merged in 2021-04, with the labels that each got.

#35 Fix/refactor navigation query selector
  .eslintrc.js
  .eslintrc.json
  README.md
  package.json
  src/ApolloSpreadsheet.tsx
  src/api/types/mergeCellsApi.ts
  src/api/types/navigationApi.ts
  src/api/useApiFactory.ts
  src/cellMeasurer/CellMeasureWrapper.tsx
  src/columnGrid/ColumnGrid.tsx
  src/columnGrid/column-grid-props.ts
  src/columnGrid/types/header.type.ts
  src/columnGrid/utils/parseColumnWidthsConfiguration.ts
  src/editorManager/__tests__/useEditorManager.spec.tsx
  src/editorManager/components/TextEditor.tsx
  src/editorManager/useEditorManager.tsx
  src/events/useEvents.ts
  src/gridContainer/GridContainer.tsx
  src/gridWrapper/GridWrapper.tsx
  src/gridWrapper/gridWrapperCommonProps.tsx
  src/gridWrapper/gridWrapperProps.ts
  src/index.tsx
  src/keyboard/NavigationMask.tsx
  src/keyboard/__tests__/navigation.utils.spec.ts
  src/keyboard/constants.ts
  src/keyboard/index.ts
  src/keyboard/types/cell-click-double-params.ts
  src/keyboard/types/index.ts
  src/keyboard/types/navigation-coords.type.ts
  src/keyboard/useKeyboard.tsx
  src/keyboard/utils/getDefaultValueFromValue.util.ts
  src/keyboard/utils/index.ts
  src/keyboard/utils/navigation.utils.ts
  src/keyboard/utils/querySelector.helper.ts
  src/mergeCells/useMergeCells.tsx
  src/mergeCells/validationErrorMessages.ts
  src/navigation/index.ts
  src/navigation/reservedKeyCodes.ts
  stories/ScrollAlignment.stories.tsx
  stories/Stretch.stories.tsx
  stories/components/Spreadsheet/Spreadsheet.tsx
  stories/components/Table/Table.tsx
  stories/components/Table/TableWithNestedRows.tsx
  stories/components/VPD.tsx
  yarn.lock
Labels: bug, enhancement

#40 Docusaurus update
  .gitignore
  docs/docs/columns.md
  docs/docs/custom-header.md
  docs/docs/doc1.md
  docs/docs/doc3.md
  docs/docs/editors.md
  docs/docs/getting-started.md
  docs/docs/input.md
  docs/docs/nested-header.md
  docs/docs/row-grouping.md
  docs/docs/row-navigation.md
  docs/docs/theme.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/pages/index.js
  docs/static/img/apollo-spreadsheet-light.svg
  docs/static/img/apollo.svg
  docs/static/img/favicon.ico
  docs/static/img/favicoon.ico
  docs/static/img/github.png
  docs/yarn.lock
  package.json
  stories/components/Table/NestedHeaders.tsx
  yarn.lock
Labels: documentation

#43 Docs
  .gitignore
  docs/docs/doc2.md
  docs/docs/getting-started.md
  docs/package-lock.json
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/static/img/apollo-spreadsheet.svg
  docs/static/img/react-ts.svg
Labels: documentation

#44 Refactoring and improvements on the types and allowing more generics …
  src/ApolloSpreadsheet.tsx
  src/api/eventConstants.ts
  src/api/types/coreApi.ts
  src/api/useApiEventHandler.ts
  src/api/useApiFactory.ts
  src/cellMeasurer/cellMeasureWrapperProps.ts
  src/columnGrid/ColumnGrid.tsx
  src/columnGrid/columnGridProps.ts
  src/columnGrid/components/SortIndicator.tsx
  src/columnGrid/components/index.ts
  src/columnGrid/hooks/index.ts
  src/columnGrid/hooks/useHeaders.tsx
  src/columnGrid/index.ts
  src/columnGrid/types/cellEditorProps.ts
  src/columnGrid/types/column-width-dictionary.ts
  src/columnGrid/types/column.types.ts
  src/columnGrid/types/gridHeader.interface.ts
  src/columnGrid/types/index.ts
  src/columnGrid/types/nestedHeader.interface.ts
  src/columnGrid/types/sort-order.ts
  src/columnGrid/utils/parseColumnWidthsConfiguration.ts
  src/data/createData.tsx
  src/data/useData.tsx
  src/editorManager/editorProps.ts
  src/editorManager/useEditorManager.tsx
  src/events/useEvents.ts
  src/gridWrapper/GridWrapper.tsx
  src/gridWrapper/interfaces/index.ts
  src/gridWrapper/interfaces/registerChildFn.ts
  src/helpers/resolveDynamicCallback.ts
  src/helpers/resolveDynamicOrBooleanCallback.ts
  src/keyboard/useKeyboard.tsx
  src/mergeCells/createMergedGroups.tsx
  src/mergeCells/createMergedPositions.ts
  src/mergeCells/useMergeCells.tsx
  src/mergeCells/validateMergeData.ts
  src/mergeCells/validationErrorMessages.ts
  src/mergeCells/validators.tsx
  src/nestedRows/depth-map.interface.ts
  src/nestedRows/icon-renderer.type.ts
  src/nestedRows/index.ts
  src/nestedRows/nestedRowsProps.ts
  src/nestedRows/useNestedRows.tsx
  src/sort/useSort.tsx
  src/types/dynamic-callback.ts
  stories/Examples.stories.tsx
  stories/ScrollAlignment.stories.tsx
  stories/Stretch.stories.tsx
  stories/components/Spreadsheet/Spreadsheet.tsx
  stories/components/Spreadsheet/createMergedCells.ts
  stories/components/Spreadsheet/dataUseCases.tsx
  stories/components/Table/Table.tsx
  stories/components/Table/TableWithNestedRows.tsx
  stories/components/VPD.tsx
Labels: documentation, enhancement

#46 Feat/remove document events
  src/ApolloSpreadsheet.tsx
  src/events/useEvents.ts
Labels: enhancement

#48 Docs main page
  docs/src/pages/index.js
  docs/static/img/react-virtualized.svg
Labels: documentation

#50 Docs
  docs/docs/doc1.md
  docs/docs/getting-started.md
  docs/docs/theme.md
  docs/docusaurus.config.js
Labels: documentation

#51 Demo
  stories/Grid.stories.tsx
  stories/Sort.stories.tsx
  stories/components/Table/MultiTheme.tsx
Labels: enhancement
